[project]
name = "tech-writer-agent-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.10",
    "binaryornot>=0.4.4",
    "google-genai>=1.19.0",
    "openai>=1.85.0",
    "pathspec>=0.12.1",
]
