[project]
name = "baseline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathspec>=0.11.0",
    "binaryornot>=0.4.4",
    "openai>=1.0.0",
]
