#!/bin/bash
# Script to create a README index of Python package agent makers

# Set the base directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OSS_AGENT_MAKERS_DIR="$(cd "$SCRIPT_DIR/../oss-agent-makers" && pwd)"
PYTHON_PACKAGES_DIR="$OSS_AGENT_MAKERS_DIR/python-packages"

echo "Creating Python packages index..."
echo "================================"

# Create python-packages directory if it doesn't exist
if [ ! -d "$PYTHON_PACKAGES_DIR" ]; then
    echo "Creating directory: $PYTHON_PACKAGES_DIR"
    mkdir -p "$PYTHON_PACKAGES_DIR"
fi

# Create README.md
README_FILE="$PYTHON_PACKAGES_DIR/README.md"
cat > "$README_FILE" << 'EOF'
# Python Package Agent Makers

This directory contains an index of agent makers that use the "Package option, Python" format.

## Agent Makers

EOF

# Track count
count=0

# Process each directory in oss-agent-makers
for dir in "$OSS_AGENT_MAKERS_DIR"/*/; do
    # Skip if not a directory
    [ ! -d "$dir" ] && continue
    
    # Get directory name
    dir_name=$(basename "$dir")
    
    # Skip the python-packages directory itself
    if [ "$dir_name" == "python-packages" ]; then
        continue
    fi
    
    # Check if metadata.json exists
    metadata_file="$dir/metadata.json"
    if [ ! -f "$metadata_file" ]; then
        continue
    fi
    
    # Extract eval_output and github_url from metadata.json
    result=$(python3 -c "
import json
try:
    with open('$metadata_file', 'r') as f:
        data = json.load(f)
        eval_output = data.get('eval_output', '')
        github_url = data.get('github_url', '')
        if eval_output == 'Package option, Python':
            print(f'{github_url}')
except:
    pass
" 2>/dev/null)
    
    # Check if we got a result
    if [ ! -z "$result" ]; then
        echo "Found Python package: $dir_name"
        
        # Add to README
        echo "- [$dir_name](../$dir_name/) - [GitHub]($result)" >> "$README_FILE"
        ((count++))
    fi
done

# Add footer to README
echo "" >> "$README_FILE"
echo "---" >> "$README_FILE"
echo "" >> "$README_FILE"
echo "_Total: $count Python package agent makers_" >> "$README_FILE"
echo "" >> "$README_FILE"
echo "_Generated by [create-python-packages-index.sh](../../setup/create-python-packages-index.sh)_" >> "$README_FILE"

echo ""
echo "Python packages index created!"
echo "Total Python packages found: $count"
echo "Index written to: $README_FILE"