[project]
name = "tech-writer-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "atomic-agents>=1.1.3",
    "google-genai>=1.20.0",
    "openai>=1.86.0",
]
